@startuml 桌面共享
participant RDP客户端 as client
box "drd-user"
participant 客户端连接管理 as listener
participant 连接安全管理 as security
participant 屏幕采集管理 as capture
participant 输入事件管理 as input
participant 编码与传输管理 as encoder
end box
participant 图形服务器 as xorg
participant 通知中心 as notify

listener -> security:配置安全参数
listener <-- security
listener -> listener:监听端口
client -> listener:客户端请求连接
alt 配置 NLA
listener -> security:校验 NLA 密码
listener <-- security:校验通过
else 未配置 NLA
listener -> notify:发通知由用户确认
listener <-- notify:用户允许
end
listener -> client:协商和握手
client --> listener
loop
listener -> capture:持续捕获屏幕
capture ->xorg:获取视频帧
capture <--xorg

capture -> encoder:编码压缩
capture <-- encoder
listener <-- capture

client <-- listener:开始共享桌面

client -> input:输入事件处理
client <-- input
end
@enduml