#!/bin/sh
set -e
# Automatically added by dh_installsystemduser/13.16
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "${DPKG_ROOT:-}" ] ; then
		# The following line should be removed in trixie or trixie+1
		deb-systemd-helper --user unmask 'deepin-remote-desktop-handover.service' >/dev/null || true

		# was-enabled defaults to true, so new installations run enable.
		if deb-systemd-helper --quiet --user was-enabled 'deepin-remote-desktop-handover.service' ; then
			# Enables the unit on first installation, creates new
			# symlinks on upgrades if the unit file has changed.
			deb-systemd-helper --user enable 'deepin-remote-desktop-handover.service' >/dev/null || true
		else
			# Update the statefile to add new symlinks (if any), which need to be
			# cleaned up on purge. Also remove old symlinks.
			deb-systemd-helper --user update-state 'deepin-remote-desktop-handover.service' >/dev/null || true
		fi
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemduser/13.16
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "${DPKG_ROOT:-}" ] ; then
		# The following line should be removed in trixie or trixie+1
		deb-systemd-helper --user unmask 'deepin-remote-desktop-user.service' >/dev/null || true

		# was-enabled defaults to true, so new installations run enable.
		if deb-systemd-helper --quiet --user was-enabled 'deepin-remote-desktop-user.service' ; then
			# Enables the unit on first installation, creates new
			# symlinks on upgrades if the unit file has changed.
			deb-systemd-helper --user enable 'deepin-remote-desktop-user.service' >/dev/null || true
		else
			# Update the statefile to add new symlinks (if any), which need to be
			# cleaned up on purge. Also remove old symlinks.
			deb-systemd-helper --user update-state 'deepin-remote-desktop-user.service' >/dev/null || true
		fi
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.16
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if deb-systemd-helper debian-installed 'deepin-remote-desktop-system.service'; then
		# The following line should be removed in trixie or trixie+1
		deb-systemd-helper unmask 'deepin-remote-desktop-system.service' >/dev/null || true

		if deb-systemd-helper --quiet was-enabled 'deepin-remote-desktop-system.service'; then
			# Create new symlinks, if any.
			deb-systemd-helper enable 'deepin-remote-desktop-system.service' >/dev/null || true
		fi
	fi

	# Update the statefile to add new symlinks (if any), which need to be cleaned
	# up on purge. Also remove old symlinks.
	deb-systemd-helper update-state 'deepin-remote-desktop-system.service' >/dev/null || true
fi
# End automatically added section
