#!/bin/sh
set -e
# Automatically added by dh_installsystemd/13.16
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = upgrade ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'deepin-remote-desktop-system.service' >/dev/null || true
fi
# End automatically added section
